AllCops:
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

BarePercentLiterals:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Max: 15
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
SignalException:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
