ClassAndModuleChildren:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 15
SignalException:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
TrailingComma:
  EnforcedStyleForMultiline: comma
