sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-trusty to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y chefdk=1.5.0-1

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  global:
    # Ignore warnings when running specs.
    - RUBYOPT="-W0"
  matrix:
    - CHEF_VERSION=12.9.38 INSTANCE=default-debian-7
    - CHEF_VERSION=12.9.38 INSTANCE=default-debian-8
    - CHEF_VERSION=12.9.38 INSTANCE=default-ubuntu-1204
    - CHEF_VERSION=12.9.38 INSTANCE=default-ubuntu-1404
    - CHEF_VERSION=12.9.38 INSTANCE=default-centos-6
    - CHEF_VERSION=12.9.38 INSTANCE=default-centos-7
    - CHEF_VERSION=current INSTANCE=default-debian-7
    - CHEF_VERSION=current INSTANCE=default-debian-8
    - CHEF_VERSION=current INSTANCE=default-ubuntu-1204
    - CHEF_VERSION=current INSTANCE=default-ubuntu-1404
    - CHEF_VERSION=current INSTANCE=default-centos-6
    - CHEF_VERSION=current INSTANCE=default-centos-7

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script: KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - before_script:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      - /opt/chefdk/embedded/bin/chef --version
      - /opt/chefdk/embedded/bin/cookstyle --version
      - /opt/chefdk/embedded/bin/foodcritic --version
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: CHEF_VERSION=12.17.44 UNIT_AND_LINT=1
